name: CRuby bindings

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-all:
    strategy:
      matrix:
        # Some tests in this repository are only run against parse.y
        # We test them here in order to not fail ruby/ruby CI.
        parser:
          - prism
          - parse.y

    runs-on: ubuntu-24.04
    steps:
      - name: Set up latest ruby head
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler: none
      - uses: actions/checkout@v5
        with:
          repository: ruby/ruby
          path: ruby/ruby
          fetch-depth: 1
      - name: Install libraries
        run: |
          set -x
          sudo apt-get update -q || :
          sudo apt-get install --no-install-recommends -q -y build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm-dev autoconf ruby
      - uses: actions/checkout@v5
        with:
          path: ruby/prism
          fetch-depth: 1
      - run: tool/sync_default_gems.rb prism
        working-directory: ruby/ruby
      - name: Build Ruby
        run: |
          ruby tool/downloader.rb -d tool -e gnu config.guess config.sub
          autoconf
          ./configure -C --disable-install-doc --with-parser=${{ matrix.parser }}
          make -j$(nproc)
        working-directory: ruby/ruby
      - name: make test-all
        env:
          RUN_OPTS: --parser=${{ matrix.parser }}
        run: make -j$(nproc) -s test-all
        working-directory: ruby/ruby
