name: Publish to npmjs.com
on:
  push:
    tags: ['v*']  # Triggers when pushing tags starting with 'v'
jobs:
  publish:
    if: github.repository == 'ruby/prism'
    runs-on: ubuntu-latest
    environment: release  # Optional: for enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: rake templates
        run: bundle exec rake templates

      - name: Set up WASI-SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz
          tar xvf wasi-sdk-25.0-x86_64-linux.tar.gz

      - name: Build the project
        run: make wasm WASI_SDK_PATH=$(pwd)/wasi-sdk-25.0-x86_64-linux

      - name: Update npm
        run: npm install -g npm@latest

      - run: npm publish
